# Form implementation generated from reading ui file 'FRAS.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 800, 601))
        self.widget.setMaximumSize(QtCore.QSize(800, 700))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.0113636, x2:1, y2:1, stop:0.167464 rgba(114, 56, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.widget.setObjectName("widget")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(0, 70, 801, 20))
        self.line.setMaximumSize(QtCore.QSize(820, 100))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(90, 10, 611, 61))
        self.label.setStyleSheet("font: 20pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(700, 20, 51, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../PyQt6/02_Qt Designer/face.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalWidget = QtWidgets.QWidget(self.widget)
        self.verticalWidget.setGeometry(QtCore.QRect(290, 120, 211, 441))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.check_camera = QtWidgets.QPushButton(self.verticalWidget)
        self.check_camera.setMaximumSize(QtCore.QSize(200, 40))
        self.check_camera.setToolTipDuration(1)
        self.check_camera.setAutoFillBackground(False)
        self.check_camera.setStyleSheet("border-radius: 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(23, 165, 200, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"Times New Roman\";")
        self.check_camera.setObjectName("check_camera")
        self.verticalLayout.addWidget(self.check_camera)
        self.register_2 = QtWidgets.QPushButton(self.verticalWidget)
        self.register_2.setMaximumSize(QtCore.QSize(200, 40))
        self.register_2.setStyleSheet("border-radius: 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(23, 165, 200, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"Times New Roman\";")
        self.register_2.setObjectName("register_2")
        self.verticalLayout.addWidget(self.register_2)
        self.train = QtWidgets.QPushButton(self.verticalWidget)
        self.train.setMaximumSize(QtCore.QSize(200, 40))
        self.train.setStyleSheet("border-radius: 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(23, 165, 200, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"Times New Roman\";")
        self.train.setObjectName("train")
        self.verticalLayout.addWidget(self.train)
        self.attendance = QtWidgets.QPushButton(self.verticalWidget)
        self.attendance.setMaximumSize(QtCore.QSize(200, 40))
        self.attendance.setStyleSheet("border-radius: 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(23, 165, 200, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"Times New Roman\";")
        self.attendance.setObjectName("attendance")
        self.verticalLayout.addWidget(self.attendance)
        self.mail = QtWidgets.QPushButton(self.verticalWidget)
        self.mail.setMaximumSize(QtCore.QSize(200, 40))
        self.mail.setStyleSheet("border-radius: 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(23, 165, 200, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"Times New Roman\";")
        self.mail.setObjectName("mail")
        self.verticalLayout.addWidget(self.mail)
        self.exit_button = QtWidgets.QPushButton(self.verticalWidget)
        self.exit_button.setMaximumSize(QtCore.QSize(200, 40))
        self.exit_button.setStyleSheet("border-radius: 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(23, 165, 200, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"Times New Roman\";")
        self.exit_button.setObjectName("exit_button")
        self.verticalLayout.addWidget(self.exit_button)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 51, 41))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../../ptu_logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "FACE RECOGNINTION ATTENDANCE SYSTEM"))
        self.check_camera.setToolTip(_translate("MainWindow", "<html><head/><body><p>On Camera</p></body></html>"))
        self.check_camera.setStatusTip(_translate("MainWindow", "This is status tip"))
        self.check_camera.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Check Your Camera Connect !</p></body></html>"))
        self.check_camera.setText(_translate("MainWindow", "Check Camera"))
        self.register_2.setText(_translate("MainWindow", "Register Student"))
        self.train.setText(_translate("MainWindow", "Train Images"))
        self.attendance.setText(_translate("MainWindow", "Attendance"))
        self.mail.setText(_translate("MainWindow", "Mail"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
